version: "3"

services:     
  rest-api:
    container_name: rest-api
    build: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
